name: Build and deploy ASP.NET Core app to Azure Web App - slotAppService

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET SDK
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3️⃣ Restore dependencies
      - name: Restore NuGet packages
        run: dotnet restore

      # 4️⃣ Build the project
      - name: Build project
        run: dotnet build --configuration Release

      # 5️⃣ Publish to folder
      - name: Publish project
        run: dotnet publish -c Release -o ./published

      # 6️⃣ Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ./published

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      # 1️⃣ Download published artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      # 2️⃣ Login to Azure using OIDC
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # 3️⃣ Deploy to Azure Web App (slot optional)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myapp-app'       # Nom de ton App Service
          # slot-name: 'myapp-slot'     # Supprime si tu veux deployer directement sur Production
          package: './published'
